version: "3.8"
services:
  db:
    image: postgres:14.2-alpine3.15
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
    volumes:
      - ~/psql/rakkeri/data:/var/lib/postgresql/data
  
  server:
    build: ./server
    environment:
      - spring_profiles_active=production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=test
      - JWT_SECRET=really_long_secret_for_the_encryption_algorithm_so_it_accepts_it
    ports:
      - 8080:8080
    depends_on:
      - db
  
  client:
    build: 
      context: ./client
      args:
        - backendurl=http://localhost:8080
    ports:
      - 3000:3000