post http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "test_user3",
    "email": "test@example.com",
    "password": "password1"
}

###

get http://localhost:8080/api/users/1/projects
Content-Type: application/json
Authorization: bearer "token"

###


post http://localhost:8080/api/login
Content-Type: application/json

{
    "username": "test",
    "password": "testpass"
}

###

get http://localhost:8080/test

