post http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "test_user3",
    "email": "test@example.com",
    "password": "password1"
}

###


post http://localhost:8080/api/login
Content-Type: application/json

{
    "username": "test_user3",
    "password": "password1"
}

###

get http://localhost:8080/test


##Authorization: Basic user:32b543c7-9848-42e9-844f-f583df2dbe32