post http://localhost:8080/api/login
Content-Type: application/json

{
    "username": "test",
    "password": "testpass"
}

###

post http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "test_user3",
    "email": "test@example.com",
    "password": "password1"
}

###

get http://localhost:8080/api/users/1/projects
Content-Type: application/json
Authorization: bearer token

###

post http://localhost:8080/api/users/1/projects
Content-Type: application/json
Authorization: bearer token

{
    "name": "New project"
}

###

post http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: bearer token

{
    "name": "New task"
}

###

put http://localhost:8080/api/tasks/1
Content-Type: application/json
Authorization: bearer token

{
    "id": 1,
    "name": "cooking modified"
}

###

post http://localhost:8080/api/trackings
Content-Type: application/json
Authorization: bearer token

{
    "startTime": "2022-04-15T09:39:15.183",
    "user": {
        "id": 1
    },
    "project": {
        "id": 2
    },
    "task": {
        "id": 2
    }
}

### POST also updates, if id is provided, because Spring refused PUT requests....

post http://localhost:8080/api/trackings
Content-Type: application/json
Authorization: bearer token

{
    "id": 1,
    "startTime": "2022-04-20T11:52:10.720Z",
    "endTime": "2022-04-20T11:52:00.720Z",
    "user": {
        "id": 1
    },
    "project": {
        "id": 1
    },
    "task": {
        "id": 1
    }
}

###

get http://localhost:8080/test

