post http://localhost:8080/api/login
Content-Type: application/json

{
    "username": "test",
    "password": "testpass"
}

###

post http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "test_user3",
    "email": "test@example.com",
    "password": "password1"
}

###

get http://localhost:8080/api/users/1/projects
Content-Type: application/json
Authorization: bearer token

###

post http://localhost:8080/api/users/1/projects
Content-Type: application/json
Authorization: bearer token

{
    "name": "New project"
}

###

post http://localhost:8080/api/projects/1/tasks
Content-Type: application/json
Authorization: bearer token

{
    "name": "New task"
}

###

put http://localhost:8080/api/projects/1/tasks/1
Content-Type: application/json
Authorization: bearer token

{
    "id": 1,
    "name": "cooking modified"
}

###

post http://localhost:8080/api/projects/1/tasks/1/trackings
Content-Type: application/json
Authorization: bearer token

{
    "startTime": "2022-04-15T09:39:15.183"
}

###


put http://localhost:8080/api/projects/1/tasks/1/trackings/3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJ0ZXN0IiwiaWF0IjoxNjUwNDU0NTM1LCJleHAiOjE2NTE2NjQxMzV9.qkjVwJ1V33VsRO8YmmmqztovSC-0siGEXpzwPYP4cSxnfJSF44S0iFt7ibmfjqEq

{
    "startTime": "2022-04-20T11:52:02.337",
    "endTime": "2022-04-20T11:52:02.337"
}

###

get http://localhost:8080/test

