name: Deploy stack to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release API
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: rakkeri-api
          heroku_email: ${{secrets.HEROKU_API_KEY}}
        env:
          HD_APP_BASE: "server"
      - name: Release Web Client
        uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: rakkeri
          heroku_email: ${{secrets.HEROKU_API_KEY}}
        env:
          HD_APP_BASE: "client"
